const HJERTESVIGT: Topic = {
  id: "Hjertesvigt",
  videos: [{ name: "hjertesvigt" }],
  active: false,
  parentOptions: [
    {
      name: "Du har",
      active: false,
      isParent: true,
      audioName: "hvaderhjertesvigt",
      time: 13,
      options: [
        {
          id: 0,
          audioName: "Du har_2",
          time: 6,
          delay: 250,
          name: "Svækket venstre hjertekammer",
          active: false,
          disabled: false,
          exclusive: true,
          radio: false,
          exclusiveTo: [],
          disableOthers: false,
          separator: false
        },
        {
          id: 1,
          audioName: "Du har_3",
          time: 7,
          delay: 250,
          name: "Svækket højre hjertekammer",
          active: false,
          disabled: false,
          exclusive: true,
          radio: false,
          exclusiveTo: [],
          disableOthers: false,
          separator: false
        },
        {
          id: 2,
          audioName: "Du har_4",
          time: 9,
          delay: 250,
          name: "Kombination af svækket venstre og højre hjertekammer",
          active: false,
          disabled: false,
          exclusive: true,
          radio: false,
          exclusiveTo: [],
          disableOthers: false,
          separator: false
        }
      ]
    },
    {
      name: "Din årsag til hjertesvigt er",
      audioName: "Din Жrsag til hjertesvigt er_01",
      time: 2,
      active: false,
      isParent: true,
      options: [
        {
          id: 0,
          audioName: "Din Жrsag til hjertesvigt er_02",
          time: 3,
          delay: 250,
          name: "Blodprop i hjertets kranspulsåre",
          active: false,
          disabled: false,
          exclusive: true,
          radio: false,
          exclusiveTo: [],
          disableOthers: false,
          separator: false
        },
        {
          id: 1,
          audioName: "Din Жrsag til hjertesvigt er_03",
          time: 2,
          delay: 250,
          name: "Åreforkalkning",
          active: false,
          disabled: false,
          exclusive: true,
          radio: false,
          exclusiveTo: [],
          disableOthers: false,
          separator: false
        },
        {
          id: 2,
          audioName: "Din Жrsag til hjertesvigt er_04",
          time: 2,
          delay: 250,
          name: "Hjerteklapsygdom",
          active: false,
          disabled: false,
          exclusive: true,
          radio: false,
          exclusiveTo: [],
          disableOthers: false,
          separator: false,
          subChoice: "",
          subOptions: [
            "hovedpulsåreklappen er forsnævret – aorta stenose",
            "hovedpulsåreklappen er utæt – aorta insufficiens",
            "hovedpulsåreklappen er både forsnævret og utæt – aorta stenose og aorta insufficiens",
            "hjerteklappen mellem venstre for- og hovedkammer er betydende utæt – mitral insufficiens",
            "hjerteklappen mellem venstre for- og hovedkammer er betydende forsnævret – mitral stenose",
            "hjerteklappen mellem højre for- og hovedkammer er utæt i betydende grad – trikuspidal insufficiens"
          ]
        },
        {
          id: 3,
          name: "Sygdomme i hjertemusklen",
          audioName: "Din Жrsag til hjertesvigt er_12",
          time: 2,
          delay: 250,
          active: false,
          disabled: false,
          exclusive: true,
          radio: false,
          exclusiveTo: [],
          disableOthers: false,
          separator: false,
          subChoice: "",
          subOptions: [
            "svag hjertemuskel – dilateret kardiomyopati",
            "tyk hjertemuskel – hypertrofisk kardiomyopati",
            "stiv hjertemuskel – hjertesvigt med bevaret pumpekraft",
            "aflejringssygdom – amyloidose",
            "aflejringssygdom - sarcoidose"
          ]
        },
        {
          id: 4,
          audioName: "Din Жrsag til hjertesvigt er_18",
          time: 2,
          delay: 250,
          name: "Forkammerklimmer (atrieflimren)",
          active: false,
          disabled: false,
          exclusive: true,
          radio: false,
          exclusiveTo: [],
          disableOthers: false,
          separator: false
        },
        {
          id: 5,
          audioName: "Din Жrsag til hjertesvigt er_19",
          time: 2,
          delay: 250,
          name: "Kemoterapi",
          active: false,
          disabled: false,
          exclusive: true,
          radio: false,
          exclusiveTo: [],
          disableOthers: false,
          separator: false
        },
        {
          id: 6,
          audioName: "Din Жrsag til hjertesvigt er_20",
          time: 2,
          delay: 250,
          name: "Bindevævssygdom",
          active: false,
          disabled: false,
          exclusive: true,
          radio: false,
          exclusiveTo: [],
          disableOthers: false,
          separator: false
        },
        {
          id: 7,
          audioName: "Din Жrsag til hjertesvigt er_21",
          time: 2,
          delay: 250,
          name: "Graviditet",
          active: false,
          disabled: false,
          exclusive: true,
          radio: false,
          exclusiveTo: [],
          disableOthers: false,
          separator: false
        },

        {
          id: 8,
          audioName: "Din Жrsag til hjertesvigt er_22",
          time: 1,
          delay: 250,
          name: "Virus",
          active: false,
          disabled: false,
          exclusive: true,
          radio: false,
          exclusiveTo: [],
          disableOthers: false,
          separator: false
        },
        {
          id: 9,
          audioName: "Din Жrsag til hjertesvigt er_24",
          time: 2,
          delay: 250,
          name: "Alkohol",
          active: false,
          disabled: false,
          exclusive: true,
          radio: false,
          exclusiveTo: [],
          disableOthers: false,
          separator: false
        },
        {
          id: 10,
          audioName: "Din Жrsag til hjertesvigt er_25",
          time: 6,
          delay: 250,
          name: "Knust hjerte syndrom - Takotsubo kardiomyopati",
          active: false,
          disabled: false,
          exclusive: true,
          radio: false,
          exclusiveTo: [],
          disableOthers: false,
          separator: false
        }
      ]
    },
    {
      name: "Du får",
      description: "For at kunne leve et godt liv med hjertesvigt, er det vigtigt, at du tager medicin. Det virker livsforlængende og stabiliserer hjertet.\nDet er vigtigt, at behandlingen fastholdes, så hjertet ikke svækkes yderligere.\nBehandlingen omfatter ofte mindst 3 og ofte flere typer af medicin.\nDe kan alle påvirke blodtrykket, og det er normalt, at du kan blive lidt svimmel ganske kort, hvis du rejser dig hurtigt op.",
      audioName: "For at kunne leve et godt liv",
      time: 32,
      active: false,
      isParent: true,
      options: [
        {
          id: 0,
          audioName: "2-seconds-of-silence",
          time: 2,
          delay: 250,
          name: "Du får flere slags medicin til at styrke hjertet og disse bør bibeholdes livslang. Medicinen kan ses på din medicinseddel.",
          active: true,
          disabled: false,
          exclusive: false,
          radio: false,
          exclusiveTo: [],
          disableOthers: false,
          separator: false
        }
      ]
    },
    {
      name: "Dine symptomer er",
      active: false,
      isParent: true,
      options: [
        {
          id: 0,
          audioName: "2-seconds-of-silence",
          time: 2,
          delay: 250,
          name: "Åndenød eller forpustethed",
          active: false,
          disabled: false,
          exclusive: true,
          radio: false,
          exclusiveTo: [],
          disableOthers: false,
          separator: false
        },
        {
          id: 1,
          audioName: "2-seconds-of-silence",
          time: 2,
          delay: 250,
          name: "Svimmelhed, når du rejser dig op",
          active: false,
          disabled: false,
          exclusive: true,
          radio: false,
          exclusiveTo: [],
          disableOthers: false,
          separator: false
        },
        {
          id: 2,
          audioName: "2-seconds-of-silence",
          time: 2,
          delay: 250,
          name: "Lavt blodtryk på grund af behandlingen – dette er ufarligt",
          active: false,
          disabled: false,
          exclusive: true,
          radio: false,
          exclusiveTo: [],
          disableOthers: false,
          separator: false
        },
        {
          id: 3,
          audioName: "2-seconds-of-silence",
          time: 2,
          delay: 250,
          name: "Angst",
          active: false,
          disabled: false,
          exclusive: true,
          radio: false,
          exclusiveTo: [],
          disableOthers: false,
          separator: false
        },
        {
          id: 4,
          audioName: "2-seconds-of-silence",
          time: 2,
          delay: 250,
          name: "Væskeophobning",
          active: false,
          disabled: false,
          exclusive: true,
          radio: false,
          exclusiveTo: [],
          disableOthers: false,
          separator: false,
          subChoice: "",
          subOptions: [
            "som fører til øget vægt og hævede ben",
            "åndenød ved selv mindre aktiviteter, fx hvis du bøjer dig forover"
          ]
        },
        {
          id: 5,
          audioName: "2-seconds-of-silence",
          time: 2,
          delay: 250,
          name: "Nedsat appetit og mavegener",
          active: false,
          disabled: false,
          exclusive: true,
          radio: false,
          exclusiveTo: [],
          disableOthers: false,
          separator: false
        },
        {
          id: 6,
          audioName: "2-seconds-of-silence",
          time: 2,
          delay: 250,
          name: "Søvnproblemer",
          active: false,
          disabled: false,
          exclusive: true,
          radio: false,
          exclusiveTo: [],
          disableOthers: false,
          separator: false
        },
        {
          id: 7,
          audioName: "2-seconds-of-silence",
          time: 2,
          delay: 250,
          name: "Træthed",
          active: false,
          disabled: false,
          exclusive: true,
          radio: false,
          exclusiveTo: [],
          disableOthers: false,
          separator: false
        }
      ]
    },
    {
      name: "Forholdsregler for dig med hjertesvigt",
      active: false,
      isParent: true,
      options: [
        {
          id: 0,
          audioName: "2-seconds-of-silence",
          time: 2,
          delay: 250,
          name: "Du må maks. indtage 1,5 liter væske på 1 døgn",
          active: false,
          disabled: false,
          exclusive: true,
          radio: false,
          exclusiveTo: [],
          disableOthers: false,
          separator: false
        },
        {
          id: 1,
          audioName: "2-seconds-of-silence",
          time: 2,
          delay: 250,
          name: "Det en god idé at veje dig dagligt",
          active: false,
          disabled: false,
          exclusive: true,
          radio: false,
          exclusiveTo: [],
          disableOthers: false,
          separator: false
        },
        {
          id: 2,
          audioName: "2-seconds-of-silence",
          time: 2,
          delay: 250,
          name: "NYHA symptomscore x 1 i ugen - specielt ved forværring",
          active: false,
          disabled: false,
          exclusive: true,
          radio: false,
          exclusiveTo: [],
          disableOthers: false,
          separator: false
        },
        {
          id: 3,
          audioName: "2-seconds-of-silence",
          time: 2,
          delay: 250,
          name: "Husk at tage din medicin",
          active: false,
          disabled: false,
          exclusive: true,
          radio: false,
          exclusiveTo: [],
          disableOthers: false,
          separator: false
        },
        {
          id: 4,
          audioName: "2-seconds-of-silence",
          time: 2,
          delay: 250,
          name: "Ved forværring kontakt læge",
          active: false,
          disabled: false,
          exclusive: true,
          radio: false,
          exclusiveTo: [],
          disableOthers: false,
          separator: false
        },
        {
          id: 5,
          audioName: "2-seconds-of-silence",
          time: 2,
          delay: 250,
          name: "Hold dig fysisk aktiv, så du bevarer effekten af din hjertetræning",
          active: false,
          disabled: false,
          exclusive: true,
          radio: false,
          exclusiveTo: [],
          disableOthers: false,
          separator: false
        }
      ]
    },
    {
      name: "Du bør veje dig hver dag ",
      description: "Din vægt skal ligge omkring {value} og vil kunne svinge med 1 kg op eller ned.",
      active: true,
      isParent: true,
      hasRange: true,
      range: [40, 180],
      value: "",
      defaultValue: 40,
      labelText: "Kg",
      options: [
        {
          id: 0,
          audioName: "2-seconds-of-silence",
          time: 2,
          delay: 250,
          name: "Din vægt skal ligge omkring",
          active: false,
          disabled: false,
          exclusive: true,
          slider: true,
          exclusiveTo: [],
          disableOthers: false,
          separator: false
        }
      ]
    },
    {
      name: "Dit blodtryk ligger omkring",
      // description: "Din hjertesvigtsmedicin virker også blodtryks sænkende og derfor vil dit blodtryk ligge lavere end hos andre.",
      active: true,
      isParent: true,
      // hasRange: true,
      // range: [80, 150],
      // value: 80,
      // defaultValue: 80,
      labelText: "",
      options: [
        {
          id: 0,
          audioName: "2-seconds-of-silence",
          time: 2,
          delay: 250,
          name: "Din hjertesvigtsmedicin virker også blodtryks sænkende og derfor vil dit blodtryk ligge lavere end hos andre.",
          active: false,
          disabled: false,
          exclusive: true,
          //  slider: true,
          exclusiveTo: [],
          disableOthers: false,
          separator: false
        }
      ]
    }
  ]
}

export default HJERTESVIGT
